### ISSUE TITLE
exception in native call form JS

### ISSUE THREAD

**Issue by wangfpp** [bastengao/react-native-serial-port-api#1]
## system info
System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 2.48 GB / 15.55 GB
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.16.2 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  SDKs:
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 28.0.3
      System Images: android-22 | Intel x86 Atom, android-23 | Intel x86 Atom, android-25 | Google APIs ARM 64 v8a, android-27 | Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

### 错误描述
值引入插件没问题　open方法调用就直接报错　exception in native call form JS
SerialPort.java:92  28  202
SerialPortApiModule.java:77

**Comment by bastengao** [comment]
https://github.com/licheedev/Android-SerialPort-API/blob/master/serialport/src/main/java/android/serialport/SerialPort.java#L92 这行报了这个错 SecurityException 运行时异常，没有捕获到。

**Comment by bastengao** [comment]
我 master 推了异常捕获和 setSuPath getSuPath 的方法，你可以试试.
