### ISSUE TITLE
Cannot convert argument of typce class com.bastengao.serialport.SerialPortWrapper

### ISSUE THREAD

**Issue by sankomil** [bastengao/react-native-serial-port-api#10]
Hi, I was able to integrate the library with my app and am even able to make calls with it as needed. However I find that whenever I make any changes to any component and then save it. I get the `Cannot convert argument of typce class com.bastengao.serialport.SerialPortWrapper` error, but hitting reload resolves this issue until I make another change. I took a photo of the error for reference:

![image](https://user-images.githubusercontent.com/43489998/115667626-a2f06a80-a378-11eb-9c78-3016ffd80e74.png)

**Comment by bastengao** [comment]
I have fix this bug. You can try reinstall this package from master again `npm install --save git+https://github.com/bastengao/react-native-serial-port-api.git`. Please tell me if it is work, I will release this patch.

**Comment by sankomil** [comment]
Hey, thanks for the fix! I haven't run into any errors with this patch.

**Comment by bastengao** [comment]
v1.2.1 has been released.
