### ISSUE TITLE
Could not find a declaration file for module 'react-native-serial-port-api'

### ISSUE THREAD

**Issue by gbw1120** [bastengao/react-native-serial-port-api#12]
import SerialPortAPI from 'react-native-serial-port-api';
----ERROR-----
Could not find a declaration file for module 'react-native-serial-port-api'. 'd:/REACT/RrNv/my63v/node_modules/react-native-serial-port-api/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-native-serial-port-api` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-serial-port-api';`ts(7016)

**Comment by bastengao** [comment]
What's this? Do you use TypeScript?

**Comment by RodrigoGCoelhoo** [comment]
Hey. I had the same problem using TypeScript

**Comment by racedaemon** [comment]
you can add a `react-native-serial-port-api.d.ts` file somewhere in the project, preferably unde the types folder, and add this code:
```ts
declare module "react-native-serial-port-api" {
  export function listener(buffer: any) {

  }
  export type openOptions = {
    baudRate?: number
    parity?: number
    dataBits?: number
    stopBits?: number
  }
  export type Subscription = {
    remove():void
  }
  export type SerialPort = {
    close():void
    getPath(): string
    onReceived(listener: listener): Subscription
    send(hex): Promise
  }
  export function open(port: string, options: openOptions): Promise<SerialPort>
}
```
Only `declare module "react-native-serial-port-api"` is required to get rid of the error but i also added some of the types from the docs.

**Comment by AndreOneti** [comment]
This problem has been fixed on PR https://github.com/bastengao/react-native-serial-port-api/pull/47
