### ISSUE TITLE
React native version

### ISSUE THREAD

**Issue by HManzano1012** [bastengao/react-native-serial-port-api#29]
Which one is the most compatible react version to work with this library? I've been trying to use it but i alway get errors when Im trying to build it.

I'm trying to build an app to 22 api version.

note: it is the first time i work with react native so im sorry if this is a dumb question

**Comment by bastengao** [comment]
Which error you got?

**Comment by HManzano1012** [comment]
i am using "npm  react-native init app" and then  "npm install react-native-serial-port-api --save" .
Then I  change 
**    buildToolsVersion = "31.0.0"
        minSdkVersion = 22
        compileSdkVersion = 31
        targetSdkVersion = 22
**
to match with the API 22 but when I tried to build i get the following:

"A problem occurred evaluating project ':react-native-serial-port-api'.
> Plugin with id 'maven' not found."

I dont know if you know what to do

**Comment by bastengao** [comment]
[It's seem](https://discuss.gradle.org/t/plugin-with-id-maven-not-found/39621). May be you should use gradle v6.*.

**Comment by HManzano1012** [comment]
i change gradle v7.* to v6.1.1 on the following files:
-./android/build.graddle
-./android/graddle/wrapper/graddle-wrapper.properties

and I tried to build again then I get the following error:
* What went wrong:
Script compilation errors:

  Line 09: import org.gradle.configurationcache.extensions.serviceOf
                             ^ Unresolved reference: configurationcache

  Line 43:       serviceOf<ModuleRegistry>().getModule("gradle-tooling-api-builders").classpath.asFiles.first()
                 ^ Unresolved reference: serviceOf

2 errors

**Comment by bastengao** [comment]
Sorry, i can help you more.

**Comment by bastengao** [comment]
@HManzano1012 I try to fix this issue and push branch `rmeove-maven-plugin-from-gradle`. You can execute `npm install "https://github.com/bastengao/react-native-serial-port-api.git#rmeove-maven-plugin-from-gradle"` to install. If it works, i will merge it and release.

**Comment by HManzano1012** [comment]
It works!!!
Thank you so much for the help

**Comment by bastengao** [comment]
I released v1.3.2
