### ISSUE TITLE
Release 1.3.2 missing from npm

### ISSUE THREAD

**Issue by chazmcgrill** [bastengao/react-native-serial-port-api#37]
Hi,

The release 1.3.2 doesn't appear to have been deployed to the npm repository:

![image](https://user-images.githubusercontent.com/24394860/200317390-47fcadfc-070d-4ef1-9b05-1049f416466c.png)

We need that maven update for one of our projects.

Cheers

**Comment by bastengao** [comment]
1.3.2 exists https://www.npmjs.com/package/react-native-serial-port-api/v/1.3.2?activeTab=versions, but it seems after 1.3.1. I released 1.3.3 to fix it.
