### ISSUE TITLE
SerialPortAPI.open returns null

### ISSUE THREAD

**Issue by SubroBlack** [bastengao/react-native-serial-port-api#6]
`[Unhandled promise rejection: TypeError: null is not an object (evaluating 'SerialPortAPI.open')]`

Stack trace:
 ```
 node_modules\react-native-serial-port-api\src\API.js:65:78 in open
  src\components\Trial.jsx:27:18 in handler

```
I am trying to access port in an android device. But the function returns null. 
Here is my code: 
`const serialPort = await SerialPortAPI.open("/dev/ttyS4", {baudRate: 9600, parity: 0, dataBits: 8, stopbits: 1 });`

**Comment by RodrigoGCoelhoo** [comment]
Did you fix the issue?
