### ISSUE TITLE
Unhandled promise rejection [Error: no permission to read or write this serial port]

### ISSUE THREAD

**Issue by sankomil** [bastengao/react-native-serial-port-api#9]
Hi, I'm trying to use `await SerialPortAPI.open('/dev/ttyS2', { baudRate: 115200 })` but always get the error `Unhandled promise rejection [Error: no permission to read or write this serial port]` and am not sure why this error is appearing. I have also added `<uses-permission android:name="com.google.android.things.permission.USE_PERIPHERAL_IO" />` permission to my Manifest file.

**Comment by bastengao** [comment]
It happens may have no read or write permission for `/dev/ttyS2`.  You can call `SerialPortAPI.setSuPath ` to set correct `su` command path to resolve this problem. Default `su` path is `/system/bin/su`.

**Comment by sankomil** [comment]
Oh great, that worked! Thanks a lot! Closing issue now.
